### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by wapmorgan** [ilsenem/snipper#1]
What if another use case for this will be like: Download my gists (means not only starred) with #hashtag.
I can explain. If I create gist with my configurations (gitconfig, editor config, etc) and some time after that want to just clone configuration, I type `snipper get gitconfig`.

**Comment by ilsenem** [comment]
I don't fully understand what stops you from adding a star to your gist with several files? `snipper get` will download as many files as you have in your gist. I'll think about adding some more configuration to where to search gists, not only starred, but it will be always your gists, not all public.

If i get you wrong, please provide more information. Thanks.

**Comment by wapmorgan** [comment]
Oh, got it. I did not notice that I can star my own gists.

**Comment by ilsenem** [comment]
Glad that I could help. :)
